version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:14.6.0-ce.0'
    restart: unless-stopped
    hostname: '192.168.1.125'
    container_name: gitlab-ce
    ports:
      - '80:80'
      - '8443:443'
    volumes:
      - './gitlab_config:/etc/gitlab'
      - './gitlab_logs:/var/log/gitlab'
      - './gitlab_data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    container_name: 'gitlab-runner'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './config_runner:/etc/gitlab-runner'
    restart: unless-stopped
networks:
  gitlab:
    name: gitlab-network
